### ISSUE TITLE
Adjust the CAIOS logo next to BST LABS on the org's Github homepage

### ISSUE THREAD

**Issue by slichtma** [BstLabs/py-dynacli#67]
The page https://github.com/BstLabs/ includes the logo for CAIOS in the upper left. This has been auto-cropped so that the edges of the image are cut off. To fix it requires some experimentation because the auto-crop behaviour of GitHub is unpredictable. Therefore it's not as easy a fix as Scott simply sharing a new file and assuming it will display correctly. Scott recommends that he and Shako try it together (schedule a Google Meet). The alternative process is for Shako to show Scott how to edit the corporate profile information, then Scott can try it himself.

Note I'veplaced this issue under DynaCli, even though it's an issue that transcends projects (there's no place to log an issue about the GitHub accounts profile info).

**Comment by ShahriyarR** [comment]
For admin access please ask Etzik to have ability to edit the settings of the organization.

This how cropping works, to be honest I do not know, how it works.

![cropping](https://user-images.githubusercontent.com/3852029/152303141-a8c0a590-2758-45e7-bbe8-93bc1fcd2831.png)

**Comment by slichtma** [comment]
@Ebega please give me access to the Github account's organization settings. I need to experiment with recropping our logo so doesn't get cut off on the home/organization page. Thanks.

**Comment by Ebega** [comment]
Hi

How do I do that? you already have owner permissions.

BR
Etzik

**Comment by slichtma** [comment]
Logo looks good now. I added wider white margins to the original png.

**Comment by slichtma** [comment]
Logo looks good now. I added wider white margins to the original png.
