### ISSUE TITLE
[DOC] [BUG]

### ISSUE THREAD

**Issue by orkhanshirin** [BstLabs/py-dynacli#76]
**Describe the documentation issue**
A clear and concise description of what is wrong with our documentation.

In the [tutorials/greetings/say](https://github.com/BstLabs/py-dynacli/blob/main/tutorials/greetings/say) file on line 18 the comment is confusing. We don't need to include dynacli.py path. Because we already did `pip3 install dynacli`. Therefore we can change `sys.path.extend([*search_path, f'{cwd}/../../src'])` to `sys.path.extend(search_path)`.

**Comment by ShahriyarR** [comment]
Could you please send a PR with your updates? Much more appreciated :)
